#!/bin/bash

#PBS -lnodes=2:ppn=8
#PBS -lwalltime=00:30:00
#PBS -qdefault

cd /users/bienz/cs491_21/cs_491_21/dense_linear_alg
module load openmpi-3.1.3-gcc-7.3.0-ciiw2oy


echo "1 Proc"
mpirun -n 1 ./cannon 1000

echo "4 Procs"
mpirun -n 4 ./cannon 1000

echo "16 Procs"
mpirun -n 16 ./cannon 1000

